theme: jekyll-theme-tactile

utterances:
 repository: "nicewook/til"
 issue-term: title   # Mapping between blog posts and GitHub issues
 theme: github-light # Utterances theme
 label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances
