name: Generate README

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Update README.md
        run: |
          go run update.go
      - name: Push the change
        run: |
          git config --global user.name 'robot-for-hsjeong'
          git config --global user.email 'nicewook@hotmail.com'
          git commit -am "auto-generation of README.md" || true
          git push
